### ISSUE TITLE
How to express invasionStage for plants?

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#1]
@qgroom @SoVDH @timadriaens what invasion stage information do we want to extract from the manual of alien plants?

This is the information we have:

<img width="370" alt="invasion stage" src="https://user-images.githubusercontent.com/600993/27175931-07d08ac4-51c1-11e7-8067-afaa36e4162b.png">

- `D/N` is information you [have already mapped](https://github.com/inbo/alien-species-checklist/blob/master/data/vocabularies/invasionStage-mapping.tsv) (filter on "plants")
- `presence_value` comes from the presence columns `Fl`, `Wa`, and `Br`, which can have `x` for present and `?` for unknown (I assume).

1. In it's most simple form, we only express that a taxon is:

- `present` = `x` for that region
- `unknown` = `?` for that region

2. But we could also take some of the information from the `D/N` column, to make more nuanced statements, such as `established`, `introduced`, `to be determined`, `unknown`. Note that even for values in `D/N` **without a question mark**, we do have question marks in the `presence_value` column (and vice versa), so we need to decide which one takes preference.

3. And finally, a lot of taxa have empty presences for regions. We could either express this as `absent` from that region, or take the more cautious approach (maybe there was no monitoring for that region) and not say anything about the occurrence of that species in that region.

Could you give some input regarding this, so we know how to basically map the above table to `occurrenceStatus` (that's the field to use right @qgroom)?

**Comment by peterdesmet** [comment]
@qgroom I'm probably mixing a number of DwC terms, so I'm definitely need your input here. 😅

**Comment by LienReyserhove** [comment]
I'm referring to #60  for a detailed discussion on how to map invasion stage combined with presence information. 

With respect to the third option, this is fully discussed in https://github.com/trias-project/alien-plants-belgium/issues/45#issuecomment-351099040 (starting from there).

So I'm closing this issue
