### ISSUE TITLE
occurrenceStatus

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#11]
Should be `extant` (= `present`) for all taxa, as`extinct` will be removed (see #9). As this is a very simple mapping, the column `occurrenceStatus` should be removed from the spreadsheet.

**Comment by peterdesmet** [comment]
If all regions have `?` (e.g. Chenopodium album L. x probstii), should the occurrenceStatus be `presence unknown`?

**Comment by qgroom** [comment]
This issue is a problem for the vocabulary we are suggesting, because if `occurrenceStatus `only refers to the date or date range in eventDate then there will never be a reason to use the `occurrenceStatus` of `extinct`. However, checklists frequently contain this information as it refers to the status at the time of publication.

Any suggestions on how best to handle this?

**Comment by peterdesmet** [comment]
Ok, there are two questions here:

1. Your question: will there ever be a reason to use `extinct` and a date range? I would think so, as you can definitely say the dodo has been extinct since 1663. For species that are extinct in a certain region (e.g. wolfs in Belgium?), I think you can still use that. And, you might not always have date information, but still like to say something is extinct.

2. My question: how should I handle the occurrence status if all regions are `?` or `blank` (see also #24)

**Comment by LienReyserhove** [comment]
To close this issue, some quick answers:

1. There are in fact species that are considered to be extinct in the manual. For these species, we use the date range between the last observation and today. See also #60 and #62 

2. When all regions are `?`, we keep the records and state that `occurrenceStatus = presence uncertain` for each region.

3. When all regions are blank, we exclude the records from the checklist. 

See also https://github.com/trias-project/alien-plants-belgium/issues/45
