### ISSUE TITLE
origin

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#12]
Valid values for this dataset are:

* `vagrant` for `D/N` = `Cas.`
* `introduced` for `D/N` = `Nat.` or `Inv.`

As this is a simple mapping, the column `origin` should be removed from the spreadsheet

**Comment by qgroom** [comment]
done

**Comment by peterdesmet** [comment]
I'm reopening this so I don't forget I should map this.

Also, how should question marks be treated?

**Comment by qgroom** [comment]
no problem, Nat? = introduced; Cas.? = vagrant

**Comment by peterdesmet** [comment]
[Mapping done](https://github.com/trias-project/alienplantsbelgium/blob/a9ee71e59b71d98d53fac54a57af2b02ff758aee/src/dwc_mapping.md#origin) but there are also `Ext.` and `Inv.` values that are currently left blank.

Also, I think I better include this mapping in the description, as it is not a term yet.

**Comment by peterdesmet** [comment]
Updated to include this in the [description extension](https://github.com/trias-project/alienplantsbelgium/blob/27c894ad73b07894d08714eacec2af6486f7d415/data/processed/description.csv). To resolve: mapping of `Ext.` and `Inv.`

**Comment by LienReyserhove** [comment]
We decided to discard `origin` and to replace it by `invasion stage` (see https://github.com/trias-project/alien-plants-belgium/issues/60#issue-295811123):

> The information needed for invasion stage is contained in D/N (degree of naturalisation) in the raw data file (see table for the terms). This information can perfectly be mapped to the Blackburn et al. (2011) vocabulary. This field is currently used for the mapping of origin in the description extension (see #12). I would discard the term origin and replace it by invasion stage

We all agreed on this, so I'm closing this issue
