### ISSUE TITLE
Create dropdown for V/I

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#13]
`V/I` = mode of introduction = pathway = establishmentMeans currently contains good values, so we won't replace this with the Blackburn et al. controlled vocabulary (as we'll also lose some granularity). The current values are not always formatted consistently however.

* [x] Clean list for formatting (e.g. remove `,...`)
* [ ] Provide as a dropdown
* [ ] Multiple values are still possible

**Comment by LienReyserhove** [comment]
At this point, we decided to integrate information from `V/I` in the description extension, and to map this values to the Blackburn et al. controlled vocabulary. We use this vocabulary for all checklist (which have pathway information) in TrIAS. In the description extension, each pathway per species is represented in one line.
