### ISSUE TITLE
establishmentMeans

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#14]
`establishmentMeans` will be based on `V/I` and:

* [x] Mapped to Blackburn et al.
* [x] Multiple values will be provided in the single `establishmentMeans` term, but separated by pipe.
* [x] This information will only be added for distribution records for Belgium (not Flanders, etc.)
* [x] Remove field `establishmentMeans` from spreadsheet

**Comment by qgroom** [comment]
mapping to V/I is fine, but we would like to leave in the question marks and the '...' and have these striped out by the conversion script.

**Comment by peterdesmet** [comment]
Ok, so question marks and dots will be ignored in the conversion: so "wool?" and "wool" will be treated equally?

**Comment by qgroom** [comment]
Yes, that's fine.

**Comment by peterdesmet** [comment]
Like to get second option from @timadriaens and @SoVDH:

How should pathways with `?` be interpreted from the Alien plants dataset? The current implementation is:

* [ ] Just question marks: `? → (blank)`
* [ ] Single value with question mark: `Hort.? → Hort.`, as a close guess.
* [ ] Multiple values with question mark: `Hort., timber? → Hort. | timber`

Note that in the [mapping you've done before](https://github.com/inbo/alien-species-checklist/blob/master/data/vocabularies/introductionPathway-mapping.tsv), you took a more cautious approach:

* `? → unknown`
* `Hort.? → unknown`
* `Hort., timber? → Hort.` (ignore timber)

**Comment by timadriaens** [comment]
Imo, the correct way of doing it would be to account for uncertainties in pathway assessment. So to choose wool and include a field "confidence level" and set it at "low", see [[this paper](https://doi.org/10.1093/biosci/biv082)] in BioScience of which you are co-authors. But that is probably a bridge too far. So if Filip can live with "wool? --> wool" than that's fine for me.

**Comment by peterdesmet** [comment]
@timadriaens correct, but there isn't a field to express confidence level. So @qgroom, can you confirm that Filip is fine with the "wool? --> wool"?

**Comment by qgroom** [comment]
I'm sure Filip would be OK with the '?'. An uncertainty field would be too
far at this point. Almost everything in a checklist is derivative, so it
all comes with some interpretation and ambiguity.
I wonder how easily people made the decision to use Darwin Core for
checklists, rathering than thinking through all of the consequences.
Quentin
