### ISSUE TITLE
Should we add info for Flanders, Brussels, Wallonia in distribution

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#15]
Information regarding `pathway`, `first record` and `most recent record` all apply to the distribution in **Belgium**. Extrapolating that information to Flanders, Wallonia and Brussels is somewhat odd. The checklist does contain minimal presence information regarding those regions ( `X` or `?`).

So the question is, do we publish distribution information about the regions:

locality | eventDate | occurrenceStatus | establishmentMeans
--- | --- | --- | ---
Belgium | 1945-2017 | casual | seed_contaminant
Flanders | implied? | implied? | implied?

Or not:

locality | eventDate | occurrenceStatus | establishmentMeans
--- | --- | --- | ---
Belgium | 1945-2017 | casual | seed_contaminant

**Comment by qgroom** [comment]
We are OK with just giving the information for Belgium in the GBIF checklist.

**Comment by peterdesmet** [comment]
That simplifies matters a lot.
