### ISSUE TITLE
Map origin (continent) to a description

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#16]

**Comment by qgroom** [comment]
The codes of Filip will not change so we can map them to human readable terms in the script. These will then be put in the description field of DwC.

**Comment by qgroom** [comment]
I've harmonized the terms in the spreadsheet and added a drop down menu to select new items. There is now a new worksheet that relates the codes to the continents.

**Comment by peterdesmet** [comment]
The mapping is now done and the values are included in the [description extension](https://github.com/trias-project/alienplantsbelgium/blob/27c894ad73b07894d08714eacec2af6486f7d415/data/processed/description.csv). Note that the mapping in the Excel file is not used and should only serve as guidance for Filip. Changing the mapping there won't update the DwC mapping!

The final mapping is discussed in #27 Closing issue.
