### ISSUE TITLE
Degree of establishment

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#18]
Won't try to map this information for now, remove column from spreadsheet.

@qgroom correct?

**Comment by qgroom** [comment]
it's gone

**Comment by peterdesmet** [comment]
Reopening this one, as I'm get a bit confused:

1. Is D/N = degree of naturalization = degree of establishment?
2. We do **not** want to provide this info, but just occurrenceStatus info (i.e. "present")

**Comment by LienReyserhove** [comment]
https://github.com/trias-project/alien-plants-belgium/issues/56

**Comment by LienReyserhove** [comment]
#56

**Comment by LienReyserhove** [comment]
Closing this issue, for further discussion see #56
