### ISSUE TITLE
Decide how to handle <yyyy and yyyy? first records dates

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#19]
Proposal:

    <1861 => 1500/1860
    ? => 1500

**Comment by qgroom** [comment]
If the MMR column has a N, N? or Ann then the date range should end in the current year.

**Comment by qgroom** [comment]
All records without a start date can start in 1500.

**Comment by peterdesmet** [comment]
@qgroom can I ignore "ca" and "?" in FR and MRR dates? So:

```
1813? -> 1813
ca. 1975 -> 1975
```

**Comment by peterdesmet** [comment]
Ok, ignore the above questions, here's the approach I took for mapping the FR and MRR to eventDate. 

* [ ] Strip `ca.` from FR/MRR: `ca. 1975 → 1975`. The year is the best guess we have.
* [ ] Strip `?` from FR/MRR: `1813? → 1813`. The year is the best guess we have.
* [ ] Strip `>` from FR/MRR: `>1940 → 1940`. Indicates after, but that year is the best guess we have.
* [ ] Strip `<` from FR: `<1868 → 1868`. Indicates before, but some years are very specific, so I think it's better to use the year for which we have a record, rather than stating it's from 1500.
* [ ] Strip `<` from MRR: `<1957 → 1957`. Even more important than FR, we should not use 1500 here, but the year.
* [ ] Replace `Ann.` or `N` in MRR with the current year: `N → 2017`
* [ ] Replace `?` values (no year) in FR/MRR with empty: `? → (blank)`

I then combine the two years as follows:

* [ ] Both FR and MRR are empty or ?: we don't make a statement about the date, `eventDate` is left blank: `? | ? → (blank)`
* [ ] FR is empty or ?, MRR is known: we use MRR as a single eventDate. It's an indication that it was observed in that year, we don't make a statement about the range: `? | 2016 → 2016`
* [ ] FR is known, MRR is empty or ?: we use FR as a single eventDate. It's an indication that it was observed in that year, we don't make a statement about the range: `1972 | ? → 1972`
* [ ] FR and MRR are known, but the same: we use a single eventDate. It was observed in that year: `1947 | 1947 → 1947`
* [ ] FR and MRR are known and different: we use a eventDate range: `1895 | 1947 → 1895/1947`

The full list of [changed values can be seen here](https://github.com/trias-project/alienplantsbelgium/blob/102a9df65e638ec0982ed9c82c6a1eda564047db/src/dwc_mapping.md#eventdate).

I think this is the most cautious approach, without losing too much information. @qgroom please check of the mappings you agree with and discuss the once you think should change.

**Comment by peterdesmet** [comment]
We discussed this at the meeting yesterday and all agreed with this approach. The above gives an overview. Closing issue.
