### ISSUE TITLE
Region distribution not always conclusive

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#24]
Even though **we won't use** the `X` and `?` information in the presence columns, I wanted to highlight that there are:

* 22 records where all 3 regions have `?`
* 2 records where all 3 regions are blank

There is not always a relation with how the `D/N` column is populated. Maybe something to look into.

**Comment by LienReyserhove** [comment]
1. When all regions are `?`, we keep the records and state that `occurrenceStatus = presence uncertain` for each region.

2. When all regions are blank, we exclude the records from the checklist. 

See also https://github.com/trias-project/alien-plants-belgium/issues/45 and https://github.com/trias-project/alien-plants-belgium/issues/11
