### ISSUE TITLE
Decide on actual values to use for establishmentMeans

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#25]
We have are four options:

1. Take values [from first checklist vocab](https://github.com/inbo/alien-species-checklist/blob/master/data/vocabularies/introductionPathway.tsv) by @SoVDH and @timadriaens: `contaminant > transportation of habitat material (soil, vegetation,…)`
2. Shorten those values (current implementation): `contaminant:habitat_material`
3. Use proposed [pathway vocab](https://github.com/qgroom/ias-dwc-proposal/blob/master/vocabulary/pathway.tsv) by @qgroom: `transportation of habitat material` (no category info in values)
4. Shorten those values...

**Comment by timadriaens** [comment]
I think it makes sense showing CBD pathway categories and subcategories in the field (which is what we did already). For many checklists, we'll probably only have category information so by including both we can still use these data.

**Comment by peterdesmet** [comment]
@timadriaens ok, that leaves options 1 and 2, and I think I prefer 2 with the more controlled short values.

**Comment by qgroom** [comment]
Yes I agree with Tim. If these are ultimately implemented in SKOS they will need a short name anyway, though less than 16 characters would be better IMHO. SKOS could also use a meaningless identifier and there is something to be said for doing this.

**Comment by peterdesmet** [comment]
So, for now you agree with using option 2? If so, I'd like a full mapping of CBD to those codes.

**Comment by timadriaens** [comment]
I do agree with using option 2
