### ISSUE TITLE
Decide on name for "origin" as description

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#26]
The [description extension](https://github.com/trias-project/alienplantsbelgium/blob/27c894ad73b07894d08714eacec2af6486f7d415/data/processed/description.csv) currently uses the type name "origin" for `vagrant`, `introduced`, etc. We need to decide if we want to keep it that way.

The name "origin" is discussed here: https://github.com/qgroom/ias-dwc-proposal/issues/5

**Comment by qgroom** [comment]
I'm OK with this terminology. It is always going to be problematic.
In most checklists the majority would be native, which would make the usage clearer.

**Comment by LienReyserhove** [comment]
We decided to discard `origin` and to replace it by `invasion stage` (see https://github.com/trias-project/alien-plants-belgium/issues/60#issue-295811123):

> The information needed for invasion stage is contained in D/N (degree of naturalisation) in the raw data file (see table for the terms). This information can perfectly be mapped to the Blackburn et al. (2011) vocabulary. This field is currently used for the mapping of origin in the description extension (see #12). I would discard the term origin and replace it by invasion stage

We all agreed on this, so I'm closing this issue
