### ISSUE TITLE
Decide on name for "native range" in description

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#27]
The [description extension](https://github.com/trias-project/alienplantsbelgium/blob/27c894ad73b07894d08714eacec2af6486f7d415/data/processed/description.csv) currently uses the type name "native range" for `Americas`, `Australasia`, etc. We need to decide if we want to keep it that way.

The name "native range" came up in this discussion: https://github.com/qgroom/ias-dwc-proposal/issues/5 and is what was [suggested as a term here](https://github.com/inbo/alien-species-checklist/blob/master/data/vocabularies/nativeRange.tsv)

**Comment by qgroom** [comment]
PlinianCore uses the term `Distribution`, but I don't feel that helps much.

**Comment by LienReyserhove** [comment]
We decided to use the term `native range` in the `description extension`. See also https://github.com/trias-project/alien-plants-belgium/issues/28
