### ISSUE TITLE
Map description extension

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#32]
Currently not published.

**Comment by peterdesmet** [comment]
The taxon description extension is not installed on the IPT, which can only be done by the IPT admin. @andrejjh or @dimevil, can you install the taxon description extension at http://ipt.biodiversity.be/admin/extensions.do:

![extension](https://user-images.githubusercontent.com/600993/30420046-b12fcdf0-9938-11e7-903d-d01f893d8081.png)

**Comment by andrejjh** [comment]
Hi Peter,
The taxon description extension installed on our IPT.
Best,

--
Ir Andre Heughebaert
Belgian Biodiversity Platform <http://www.biodiversity.be>
+32(0)2238 3796
Av. Louise 231 Louizalaan
B-1050 Brussels ORCID 0000-0002-7839-5300
<http://orcid.org/0000-0002-7839-5300>

**Comment by peterdesmet** [comment]
Thanks!
