### ISSUE TITLE
Difference in number of taxa: source <-> GBIF

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#34]
The source dataset has [2,500 records](http://ipt.biodiversity.be/resource?r=alien-plants-belgium) (= taxa), while on GBIF it is displayed as [2,653](https://www.gbif.org/dataset/9ff7d317-609b-4c08-bd86-3bc404b77c42). We have to figure out why.

**Comment by peterdesmet** [comment]
Now reduced on GBIF to [2481](https://www.gbif.org/dataset/9ff7d317-609b-4c08-bd86-3bc404b77c42) taxa: not sure why there is still a difference... hybrids?

**Comment by LienReyserhove** [comment]
I thought this issue was solved, i.e. GBIF automatically adds higher taxonomical levels to the records. Although it's funny that GBIF registers less taxa than we added species. @peterdesmet could you confirm this?

**Comment by peterdesmet** [comment]
I see 2.522 source records and 2.522 GBIF records. So correct!
