### ISSUE TITLE
Resource is registered with BBPF instead of BGM

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#37]
The [resource](http://ipt.biodiversity.be/resource?r=alien-plants-belgium) is currently registered with the BBPF. @DimEvil @andrejjh, can you register this with the Botanic Garden Meise instead?

**Comment by DimEvil** [comment]
@andrejjh @niconoe  (Could you do this, I don't have the possibility here)

*Instructions for migrating a DwC archive from one publisher to another in IPT.*

2. Update the <organisation> element in the resource.xml file, replacing the organization key (GBIF UUID) of the old organization with the key (GBIF UUID) of the new one.
 
For example changing <organisation>2760d7b0-767c-11d8-a198-b8a03c50a862</organisation> to <organisation>6b2f029b-7823-4b84-9c30-31ff364238fe</organisation> changes ownership from http://www.gbif.org/publisher/2760d7b0-767c-11d8-a198-b8a03c50a862 to http://www.gbif.org/publisher/6b2f029b-7823-4b84-9c30-31ff364238fe

 
To locate your resource.xml file, look inside the resources folder inside your IPT data directory. For example, if C:\IPT-Data is your data directory, and the resource being updated has short hand ‘allan_herbarium’, the resource.xml file would be located at C:\IPT-Data\resources\bruxelles\resource.xml

 
3. Save the resource.xml file and ensure the file permissions are the same as before

4. Restart your servlet container (e.g. Tomcat)

5. Login to the IPT, and if it looks like the organization switch was successful try to republish the resource again

**Comment by niconoe** [comment]
Indeed, seems a good move. @silenius, can you have a look since it involves manually changing a file on the server?

Just to be safe, I'd also like that we inform the secretarial after the manual change so they can check everything's fine on their side.
