### ISSUE TITLE
ID's in the manual

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#38]
Reported by @DimEvil at https://github.com/inbo/alien-species-checklist/issues/87:

> Are we sure we would like ID's like 1,2,3.....
> I would propose to make the
> ID's more unique....

**Comment by peterdesmet** [comment]
IMO a locally unique ID is easier to create and maintain (it's maintained in an Excel file after all). It makes the scope (= local) very clear to anyone who has to maintain this in the future, while adding an artificial prefix might make a future (or even current) maintainer wonder if that is actually used. The only prefix I'd consider useful is a URL that then makes the ID actionable (you can click it to find more info about that record), cf. VASCAN: taxonID in DwC is e.g. `12792`, while actionable ID is http://data.canadensys.net/vascan/taxon/12792.

Also, records in this dataset will get a globally unique clickable identifier by GBIF: https://www.gbif.org/species/134086869: that one might be worth adding to the source dataset, but it can become a pain to maintain. 😄

**Comment by DimEvil** [comment]
Check: http://rs.gbif.org/extension/gbif/1.0/distribution.xml
"A code for the named area this distributon record is about. Use a prefix for each code to indicate the source of the code, see http://rs.gbif.org/areas/ for list of coding schemes and their recommended prefix. see also http://rs.gbif.org/areas/"

The interpreted resource can't be downloaded through GBIF (at the moment) . so if you download the original resource , you get 1,2,3...as ID which I don't encourage.

It's the same for taxonID's used in the manual. 1,2,3 is never a taxonID...

A unique identifier for the set of nomenclatural and taxonomic information (data associated with the Taxon class). A taxonID refers to a name being used somewhere, therefore not precluding whether it is a taxon (concept) or name alone that is being described. This also includes both accepted taxon references and references to synonyms. If possible a **globally unique ID is preferred**, but local IDs are valid as long as they are unique within the dataset. It is possible for two different taxonID rows to refer to the same scientificName if they refer to different taxon concept circumscriptions referenced in nameAccordingTo. see also http://rs.tdwg.org/dwc/terms/index.htm#taxonID

**Comment by DimEvil** [comment]
I'm ok in using localID's, but they should not be 1,2,3.. :) even in the local database...

**Comment by peterdesmet** [comment]
taxonIDs will be of the form `alien-plants-belgium:taxon:1`. Closing issue.
