### ISSUE TITLE
Stable IDs in the manual

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#44]
Taxon IDs are currently stored in the Excel file. However, when new species are added (alphabetically), the ID column is reassigned by Filip, so all IDs run again from 1 to x. That means that almost all species get assigned new IDs.

Option 1: Explain Filip that those IDs should be kept stable, but that requires manual addition of new IDs... which will eventually lead to duplicates or gaps.

Option 2: Generate an ID (hash) in the R script, based on the scientific name. If a name gets updated, it gets a new ID (which is logical, except for typographic corrections, but we can live with that). Has the advantage that records won't change in git every time the ID column gets recalculated.

I prefer option 2.

Have asked GBIF if `taxonID` is even used to assign `taxonKey`s in GBIF: https://github.com/gbif/portal-feedback/issues/688

**Comment by peterdesmet** [comment]
See [this answer](https://github.com/gbif/portal-feedback/issues/688#issuecomment-348147752): taxonKeys at GBIF are based on our taxonIDs, so it is important to keep them as stable as possible! We could still go for option 1 or 2, to be discussed with Filip. @LienReyserhove can you email Filip and Quentin and ask what they prefer?

**Comment by LienReyserhove** [comment]
I will update Filip and Quentin on this issue. Personally, I prefer option two as this appears to be the most stable solution to me, especially because there is no room for errors due to manual editing. We have to think about good and unique identifiers for each scientific name though...

**Comment by qgroom** [comment]
Filip is out of the country at the moment, but it would be good to have a
discussion with him when he returns. Lien, would you like to visit the
Garden one day? You could chat to Filip about his dataset, but we could
also discuss other data the Garden has and how we could mobilize it.
Quentin

**Comment by LienReyserhove** [comment]
I think this is a very good idea. I'm willing to come to the botanic
garden, so please name a date that would fit you!
Cheers,
Lien

**Comment by qgroom** [comment]
OK, I'll contact Filip and get back to you with a suggestion.
Quentin

**Comment by LienReyserhove** [comment]
#50

**Comment by LienReyserhove** [comment]
As agreed in our meeting, I integrated the new taxonID (i.e. alien-plants-belgium:taxon:HASH) in the mapped dataset, see #50
