### ISSUE TITLE
fields FL, Br, WA

### ISSUE THREAD

**Issue by timadriaens** [trias-project/alien-plants-belgium#45]
Hi there, as you know the idea is also to use the checklists to feed regional biodiversity indicators. Therefore, these fields are important to us to include. For a number of the other checklists, we can infer them: the non-native fish are for Flanders only, the macroinvertebrates as well so these are all Fl: present. Inferring this from the occurrences will not work, as many species figure on checklists based on published information rather than occurrences. Is it still possible to include this @peterdesmet ?

**Comment by peterdesmet** [comment]
This is how we've set the distribution so far:

* Macroinvertebrates: Flanders
* Non-native fish: (will be) Flanders
* Manual of alien plants: Belgium

For the manual, we chose Belgium because the related information (first date, last date, pathway) is for Belgium:

    1	ISO_3166-2:BE	Belgium	BE	present	escape:horticulture	1998/2016

If we want to include the regional information, it would have to be like this:

    1	ISO_3166-2:BE	        Belgium	                BE	present	escape:horticulture	1998/2016
    1	ISO_3166-2:BE-VLG	Flemish Region	        BE	present
    1	ISO_3166-2:BE-WAL	Walloon Region	        BE	present
    1	ISO_3166-2:BE-BRU	Brussels-Capital Region	BE	unknown or absent

Meaning:

* We would have to add the regional information after Belgium (OK)
* The regional information would only have occurrenceStatus (no date or pathway)
* We need to decide what to do with empty regions: e.g. if Brussels has no X: is it not there or is that not assessed?

@timadriaens what do you think? See also #15 and the decision @qgroom took there. But we can always change that.

**Comment by timadriaens** [comment]
I think that indeed we should eventually keep the information for Belgium for the checklist. Yet, regional information can be inferred and that information is necessary to draft regional indicators or in case we want to have the option to select on region. In case a species is only present in one region we can assume date and pathway relate to that region and so we could keep lines for belgium and for the region with occurrenceStatus populated. Empty regions: this is to check with Quentin/Filip but I assume an empty region simply means 'absent' (in the sense 'not reported').

**Comment by peterdesmet** [comment]
Ok @LienReyserhove, can you try to include this information [as described by Tim](https://github.com/trias-project/alien-plants-belgium/issues/45#issuecomment-348928847)?

**Comment by qgroom** [comment]
No X means absent, but as always with absences it is not an absolute.
Certainly, all speces have assessed for all regions and no X does not mean
that it hasn't been looked for.
Quentin

**Comment by LienReyserhove** [comment]
I made a first attempt to deal with this issue in a new pull request, i.e. #47

**Comment by peterdesmet** [comment]
@qgroom what should we do with absence information (no `X`) now?

1. Don't add this region to the distribution extension (current implementation)
2. Add this region to the distribution extension, with occurrenceStatus: "absent"

**Comment by timadriaens** [comment]
Option 1 seems preferable to me as the absences are not absolute

**Comment by qgroom** [comment]
I actually favor option 2, but for the same reasons Tim prefers option 1.
Although the field is empty all the evidence has been checked. The only
problem is in deciding what dates to use.
Quentin

**Comment by peterdesmet** [comment]
No date info would be provided, just like we don’t provide it for presence in the regions (except if there is only one region).

**Comment by LienReyserhove** [comment]
At this point, we decided to not add the absence information to the dataset (option 1)
