### ISSUE TITLE
Add degree of establishment

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#56]
Add `degree of establishment` to the description extension, with the values:

- established
- introduced
- data deficient (which includes to be determined by experts)

I don't remember on which field in the Excel this was based, but it should be in the Google Doc by Tim. I also don't know the name of the used vocabulary (if any).

**Comment by peterdesmet** [comment]
@timadriaens @qgroom @SoVDH don't recall how to call this: `degree of establishment` or `invasion stage`?

**Comment by qgroom** [comment]
'established' is a term that expresses the degree of establishment or invasion stage
'introduced' is to do with where is comes from and says nothing about the degree of establishment or invasion stage.
The two terms are not mutually exclusive.

**Comment by peterdesmet** [comment]
Ok, guess we need a vocab to better express degree of establishment.

**Comment by LienReyserhove** [comment]
At this point I would suggest to use (for each checklist):

*  establishmentMeans: introduced
*  invasion stage: established

see also https://github.com/trias-project/alien-fishes/issues/6

**Comment by peterdesmet** [comment]
@LienReyserhove agreed that this is the general approach for each checklist. For the manual of alien plants, there is this comment on invasion stage in the document:

> the 64 spp from MAP noted “inv.”: (definition Manual) Inv. (invasive): naturalized taxa that penetrate and proliferate in (semi-) natural habitats, not necessarily causing damage. Taxa that are found only occasionally or temporarily in (semi-) natural habitats are not considered as such (for instance Coronopus didymus)
> yet, for some species this seems not correct (e.g. Egeria) for Belgium → established

@timadriaens @qgroom does this translate in putting all plants as invasion stage `established`?

@LienReyserhove: when adding `invasion stage` to the Rmd, please add an explanation like you did for alien fishes: it's really helpful.

**Comment by LienReyserhove** [comment]
See discussion in https://github.com/trias-project/alien-plants-belgium/issues/60.
We are now integrating `invasion stage` rather than `degree of establishment`. #60 gives a detailed overview of how we interpret the invasion stage information contained in the MAP. 
I'm closing this issue now.
