### ISSUE TITLE
Add speciesProfile information

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#59]
@qgroom can you ask Filip to add a column to the source file called `environment`, with the following 3 values:

* `M` for `isMarine`
* `F` for `isFreshwater`
* `T` for `isTerrestrial`

The column can contain multiple values, such as `F/T`, separated by `/`.

We will use this information to populate the http://rs.gbif.org/extension/gbif/1.0/speciesprofile.xml

---

Note: we will also indicate `FALSE` if something is not indicated, so `T` will have:

* isMarine: false
* isFreshwater: false
* isTerrestrial: true

**Comment by LienReyserhove** [comment]
Integrated, see #68
