### ISSUE TITLE
Add column hybridFormula

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#6]
The column `Taxon` sometimes contains the hybrid formula between parenthesis.

    Taxon: Chenopodium x preissmannii J. Murr (C. album L. x opulifolium)

This will make it difficult for the GBIF name parsing, so it's better to move this information to a separate column:

    Taxon: Chenopodium x preissmannii J. Murr
    HybridFormula: C. album L. x opulifolium

For hybrid without a name, both columns should be populated with the same info:

    Taxon: Chenopodium album L. x hircinum
    HybridFormula: Chenopodium album L. x hircinum

Ideally, the HybridFormula should also be more complete consistent, like `Chenopodium album L. x Chenopodium opulifolium L.`

Note: the hybridFormula information will **not** be mapped to published data.

**Comment by peterdesmet** [comment]
qgroom, let me know if you need help parsing/cleaning this information

**Comment by peterdesmet** [comment]
Thanks @qgroom for moving the hybrid formula info to its own column in the new Excel file.

**Comment by qgroom** [comment]
Funnily enough I seconded a proposal at the Nomenclatural Section of the IBC to make a recommendation in the International Code that hybrid formulas should be written like this Chenopodium album L. x Chenopodium opulifolium L.
Therefore, we will be following the next ICBN by making it this way.

**Comment by peterdesmet** [comment]
👍
