### ISSUE TITLE
Add invasion stage

### ISSUE THREAD

**Issue by LienReyserhove** [trias-project/alien-plants-belgium#60]
**Suggestion**: add `invasion stage` to the description extension. The mapping would look like this (`occurrenceStatus `and `establishmentMeans `in distribution extension):

raw data (D/N) | invasion stage | occurrenceStatus | establishmentMeans
--- | --- | --- | --- |
Cas. | Casual | present | introduced
Cas.? | Casual | present | introduced
Ext / Cas. | Casual | present | introduced
Ext |  | **absent** | introduced
Ext? |  | **absent** | introduced
Inv. | established | present | introduced
Nat? | established | present | introduced
Nat. | established | present | introduced
Nat.? | established | present | introduced

### Background:

In the latest TrIAS core group meeting, we decided to integrate `invasion stage` in the description extension of the Manual of Alien Plants. Similar as for the [Registry of Alien Macroinvertebrates in Flanders, Belgium](https://github.com/trias-project/alien-macroinvertebrates) and the [Checklist of Non-native Freshwater Fishes in Flanders, Belgium](https://github.com/trias-project/alien-fishes-checklist), we use the invasion stage vocubulary listed in [Blackburn et al. 2011](http://doc.rero.ch/record/24725/files/bach_puf.pdf).

To integrate `invasion stage` in the description extension, we need to make to some decisions:

### Discard origin information:

The information needed for `invasion stage` is contained in `D/N` (degree of naturalisation) in the raw data file (see table for the terms). This information can perfectly be mapped to the Blackburn et al. (2011) vocabulary. This field is currently used for the mapping of `origin` in the description extension (see https://github.com/trias-project/alien-plants-belgium/issues/12). I would **discard the term origin** and **replace it by invasion stage**

### Interpretation of D/N values:

1. For the previous checklists, we used the invasion stages `casual` and `established`. We decided to discard the terms `naturalized` or `invasive` listed in Blackburn et al. (see https://github.com/trias-project/alien-fishes-checklist/issues/6#issuecomment-358610670). So, `naturalized` and `invasive` in `D/N` are replaced by `established`. `casual` in `D/N`, of course, remains `casual`.

2. `D/N = Extinct` has no alternative in Blackburn et al. (2011). For this, I would leave `invasion stage` empty and supplement the information with information in `occurrenceStatus` and `establishmentMeans` (see table on top). See [occurrenceStatus GBIF vocabulary](http://rs.gbif.org/vocabulary/gbif/occurrence_status.xml): "An extinct organism is absent while its establishmentMeans is native". Of course, as we are working with invasive species, `establishmentMeans` would be `introduced` in this case.

3. We "ignore" the question marks in 'D/N' (see https://github.com/trias-project/alien-plants-belgium/issues/12#issuecomment-313702127)

**Comment by qgroom** [comment]
> For the previous checklists, we used the invasion stages casual and established. We decided to discard the terms naturalized or invasive listed in Blackburn et al. (see trias-project/alien-fishes-checklist#6 (comment)). So, naturalized and invasive in D/N are replaced by established. casual in D/N, of course, remains casual.

I can remember why you liked "invasion stage", rather than the more neutral term "degree of establishment".

> D/N = Extinct has no alternative in Blackburn et al. (2011). For this, I would leave invasion stage empty and supplement the information with information in occurrenceStatus and establishmentMeans (see table on top). See occurrenceStatus GBIF vocabulary: "An extinct organism is absent while its establishmentMeans is native". Of course, as we are working with invasive species, establishmentMeans would be introduced in this case.

I think this is the best approach, though you may consider "not applicable" instead of leaving it blank.

> We "ignore" the question marks in 'D/N' (see #12 (comment))

Yes

**Comment by peterdesmet** [comment]
If we can define the following groups in the data, I would standardize them as such:

## 1. present and naturalized

- distribution with occurrenceStatus: `present` from `start_date` until `end_date` (often now)
- invasion stage: `established`

## 2. present and casual

- distribution with occurrenceStatus: `present` from `start_date` until `end_date` (often in the past)
- invasion stage: `casual`

## 3. Once naturalized, now present as casual

Mapped exactly like group 2 "present and casual"

- distribution with occurrenceStatus: `present` from `start_date` until `end_date` (often in the past)
- invasion stage: `casual` We cannot link an invasion stage with a distribution, so we take most recent invasion stage.

## 4. Once naturalized, now uncertain (needs reassessment)

- distribution with occurrenceStatus: `present` from `start_date` until `end_date` (last check)
- distribution with occurrenceStatus: `doubtful` from `end_date` until `now`
- invasion stage: `established` We cannot link an invasion stage with a distribution, so we take most recent invasion stage.

## 5. Once established, now absent/extinct

- distribution with occurrenceStatus: `present` from `start_date` until `end_date` 
- distribution with occurrenceStatus: `doubtful` from `end_date` until `now`
- invasion stage: `established` We cannot link an invasion stage with a distribution, so we take most recent invasion stage.

Thoughts? We would need to indicate how to differentiate them in the data.

**Comment by qgroom** [comment]
I assume you made these categories up?
This is that issue that you are referring to the situation at the publication date of the checklist, but the other information in the checklist is referring to the situation at the event date of the record.
Why do we need this?
Why can't we derive this information from observations?

**Comment by peterdesmet** [comment]
1. Yes, we made those up.
2. Yes, ideally we can retrieve this information from observations, but it will be less complete for all taxa.
3. Yes, we are struggling to combine statements with the time period to which they apply. This is a problem in the Excel file too!! If something is established, but has presence `?`: is it uncertain now, but established in the past, etc.? It gets complex, but we should at least be able to say a species is **no longer occurring now**.

**Comment by LienReyserhove** [comment]
Ok, I made an effort to summarize all possible combinations in the dataset, together with how this would translate into the Darwin Core Mapping.  I now distinguish 5 different mapping categories:

(in the table: DN = degree of naturalization, FR = date first record, MRR = date most recent record. First 3 columns are included in the raw data)

### 1. Casual and presence uncertain

eventDate: populated only when the dates are provided (not `?`).

At this point, we did not populate eventDate when the presence status was `?`. However, I think it is informative to provide the dates even if we're not certain about its invasion stage or presence status. It indicates that the species might have been present (but unsure). 

DN | FR | MRR | presence | eventDate | Invasion Stage | occurrenceStatus
--- | --- | --- | --- | --- | --- | --- | 
casual | ? | ? | ?  | | casual | presence uncertain
casual | yyyy | yyyy | ?| yyyy/yyyy | casual | presence uncertain
casual? | ? | ? | ? | | casual | presence uncertain
casual? | ? | yyyy (recent records) | ? | yyyy | casual | presence uncertain

### 2. Casual and present

eventDate: populated only when the dates are provided (not `?`).

In case of the extinct/casual: the first date in eventDate is the most recent record. 
See manual of alien plants:

> Some of these extinct taxa are no longer considered as naturalized but **still occur as casuals**; such taxa are indicated as “Ext./Cas.” (for instance Tragopogon porrifolius). 

DN | FR | MRR | presence | eventDate | Invasion Stage | occurrenceStatus
--- | --- | --- | --- | --- | --- | --- | 
casual | ? | ? | present | | casual | present
casual | ? | yyyy (recent records) | present | yyyy | casual | present
casual | yyyy | yyyy | present | yyyy/yyyy | casual | present
casual?  | ? | ? | present | | casual | present
casual? | ? | yyyy (recent records) | present | yyyy | casual | present
casual? | yyyy | yyyy (recent records) | present |yyyy/yyyy | casual | present
ext / cas. | yyyy | yyyy (recent records) | present | **yyyy/now** | casual | present

### 3. Established and present

Extinct species:

>Ext. (extinct): introduced taxa that once were naturalized (usually rather locally)
but that have not been confirmed in recent times in their known localities. Only
taxa that are certainly extinct are indicated as such

Extinct/casual species: within the given time period, the species was considered to be naturalized (see 2.)

For degree of `naturalization = invasive / naturalized`, we use `invasion stage = established`.

DN | FR | MRR | presence | eventDate | Invasion Stage | occurrenceStatus
--- | --- | --- | --- | --- | --- | --- | 
extinct | yyyy | yyyy | present | **yyyy/yyyy**| established | present
ext / cas. | yyyy | yyyy (recent records) | present | **yyyy/yyyy** | established | present
invasive | yyyy | now | present | yyyy/yyyy | established | present
naturalized | ? | now | present | yyyy | established | present
naturalized? | yyyy | now? | _present_ | _yyyy_ | established | present

### 4. Confirmed extinct species

Extinct species:

DN | FR | MRR | presence | eventDate | Invasion Stage | occurrenceStatus
--- | --- | --- | --- | --- | --- | --- | 
extinct | yyyy | yyyy | present | **yyyy/now** | NA | absent

### 5. Unsure

This is a little bit odd, the species is said to be naturalized, but we hove no date and the presence status is uncertain. This is only one record though...

DN | FR | MRR | presence | eventDate | Invasion Stage | occurrenceStatus
--- | --- | --- | --- | --- | --- | --- | 
naturalized | ? | ? | ? | | ?? | presence uncertain

**Comment by peterdesmet** [comment]
Looks good. I've bolded the two cases where we ADD an extra distribution for `yyyy/now`, i.e. for those species that were once established, but are now ext/casual or ext.

@LienReyserhove I also completed the last row of the table in 3 (italic). Can you verify this is correct?

**Comment by qgroom** [comment]
I agree, this looks good. I'm now wondering how generally applicable this is.

**Comment by LienReyserhove** [comment]
@peterdesmet yes your completion is correct, thank you for his!
If I interpret this correct, I have a green light to integrate these changes in the script. 
I'm closing this issue and I will start right away!

**Comment by peterdesmet** [comment]
Good luck! Best to structure it as simple as possible in the Rmd.

**Comment by peterdesmet** [comment]
@qgroom: something Lien and I discussed further: although both invasion stage (established, casual) and occurrence status (present/absent) are time related, we unfortunately cannot express this neatly in a single extension:

- **distribution extension**: has time information (and occurrence status), but no field to express invasion stage
- **description  extension**: has invasion stage, but no field to express time... The only option is to include year info in the description itself: `established (yyyy/yyyy)`. And that doesn't solve the fact that the info is pulled away from the distribution.

So for an established species that is now casual, we have:

```perl
distribution 1    yyyy/yyyy    present
distribution 2    yyyy/now     present # looks oddly the same except for the date

description 1    established (yyyy/yyyy) # clutters description with date information
description 2    casual (yyyy/now)
```

However, the vocabulary for [occurrenceStatus](http://rs.gbif.org/vocabulary/gbif/occurrence_status.xml) includes more than present/absent: present also has the GBIF allowed subclasses `common`, `rare`, `irregular`. I know you think this inflates occurrence status with establishment, but until new terms/vocabs are available, it does allow us to more intuitively express the information:

```perl
distribution 1    yyyy/yyyy    common # subclass of present, can be used for established species
distribution 2    yyyy/now     rare   # subclass of present, has "casual" as synonym

description 1    casual
```

That way, it is clear why we have 2 different distribution records (that is not clear in the first example) and the information is still compatible with GBIF. We can argue whether "casual" should be translated to "rare" or "irregular" (= has synonym "vagrant").

The description extension can still be used to express **our** invasion stage. I would only populate it with the current invasion stage though.

Thoughts?

**Comment by qgroom** [comment]
It is a thorny problem. I feel we are getting too Procrustean with our data. Would it help to discuss this with GBIF. If there some way we could adjust the extension definitions, without changing the DwC standard that would allow for a more elegant structure? It is had to foresee all the problems with the options without discussing this. BTW: I really hate the `occurenceStatus` vocab that GBIF uses!

**Comment by LienReyserhove** [comment]
fyi, I made a [new branch](https://github.com/trias-project/alien-plants-belgium/tree/invasion-Stage-/-occurrenceStatus)  with the changes as suggested in https://github.com/trias-project/alien-plants-belgium/issues/60#issuecomment-370793343.

**Comment by peterdesmet** [comment]
> If there [is] some way we could adjust the extension definitions, without changing the DwC standard that would allow for a more elegant structure?

Indeed, especially the [distribution extension](http://rs.gbif.org/extension/gbif/1.0/distribution.xml_. It currently already has a couple of non-DwC fields: `threatStatus `, `appendixCITES` and `source`. I think it would make sense to add `invasionStage` as an extra distribution and time-related field.

What do we do in the meantime? Conflating everything into `present` is more procrustean (I'll probably have to look up that work every time you use it 😄 ) than using `common`, but we could do that for now (because you hate the vocab). For the description extension, I would already decide to only use the most recent invasion stage, so we don't have to add date information _in_ the description.

**Comment by timadriaens** [comment]
interesting discussions hat I don't think the GRIIS checklists consider, see their [Matching of data fields and terms ](https://www.nature.com/articles/sdata2017202/tables/2). They do have impact ("isInvasive") but no introduction dates nor pathway information.

**Comment by LienReyserhove** [comment]
### To conclude:

1. We decided to use the **recent** invasion stage **only** for the `extinct `or `extinct/casual` species (see #62)

2. We suggested a new vocabulary for some of these terms or to extend the existing vocabulary. For a full overview of this approach, see https://github.com/trias-project/vocab/issues/3

3. For now, we decided to keep our approach with respect to `occurrenceStatus`.
