### ISSUE TITLE
Add taxonRank dropdown

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#7]
taxonRank is a [required term](http://www.gbif.org/publishing-data/quality#checklist). The suggestion vocabulary is [this one](http://rs.gbif.org/vocabulary/gbif/rank_2015-04-24.xml) but it does not contain hybrids. We need this information for preparsing some of the names (in case the GBIF parsing fails)

Suggestion for terms:

    genus
    species
    subspecies
    variety
    cultivar
    hybrid             own term
    hybridFormula      own term

**Comment by qgroom** [comment]
I've implemented a controlled vocabulary with a dropdown menu.
Still need to sort out the hybrid formulas.

**Comment by peterdesmet** [comment]
Thanks. I notice that hybrid formulas are indicated as `hybrid`, which is fine to me. Do you want to leave it as that?
