### ISSUE TITLE
D/N information should apply to year range

### ISSUE THREAD

**Issue by peterdesmet** [trias-project/alien-plants-belgium#9]
As discussed with @groom, the degree of naturalization (`D/N`) should apply to the year range defined by `FR` (first record) and `MRR` (most recent record).

Currently it is confusing if a casual taxon with an MRR of e.g. 1945 should be labelled `extinct` or `casual`. The best way is to indicate what the status was of that taxon for that time period:

    1944    1957    casual

That also means that none of the taxa should be labelled as `extinct`.

This information should be updated.

**Comment by qgroom** [comment]
In the case where a taxon is extinct would there be a down side if we generated a second record with an event date of MMR+1 to the current year?

**Comment by peterdesmet** [comment]
That is indeed one of the options we discussed. It would be created by the script for every taxon that does not have a MMR = this year.

**Comment by qgroom** [comment]
I'm beginning to wonder if we actually need 'extinct' in the occurenceStatus vocabulary. If occurenceStatus only refers to the specified dates and place, then perhaps we only need 'extant', 'presence uncertain' and 'absent'.

**Comment by peterdesmet** [comment]
Well, "extinct" is a subcategory of "absent" in my opinion, with the extra implied info that it was "extant" before.

Btw, I know it's the IUCN vocab, but "present" is a lot more intuitive to me than the term "extant". I suggest we accept "present" as a synonym term?

**Comment by qgroom** [comment]
Indeed, I just don't feel it is good to make the implication about an earlier period when we want people to create DwC records that only refer to the place and time specified in the record.

I agree about present verses extant. I think they can be considered exact synonyms on SKOS.

**Comment by peterdesmet** [comment]
Updated occurenceStatus `extant` to `present`  in 5485d205617aca65604f214a59429dea9b920464, closing this issue.
